### ISSUE TITLE
游戏版本问题

### ISSUE THREAD

**Issue by SansPapyrus** [ZengXiaoPi/Determination-Site#7]
Undertale:False Reset的版本不是最新的
我在gamejolt上下载到了0-2-5版本，比现在网站上的新

**Comment by ZengXiaoPi** [comment]
请提供gamejolt链接

**Comment by SansPapyrus** [comment]
https://gamejolt.com/games/falsereset/585256

**Comment by ZengXiaoPi** [comment]
done
