### ISSUE TITLE
希望添加游戏

### ISSUE THREAD

**Issue by SansPapyrus** [ZengXiaoPi/Determination-Site#8]
LifeField Papyrus·Campbell Fight
魄殁无功 帕派瑞斯·坎贝尔战
https://www.bilibili.com/video/BV1Rd4y1v7L9/
https://gamejolt.com/games/11876/755475
游戏制作：庄严的承诺 
主弹幕设计：云
LifeField／魄殁无功
杉斯·坎贝尔都有了加个帕派瑞斯·坎贝尔正常吧（

**Comment by ZengXiaoPi** [comment]
done
